### ISSUE TITLE
Selective Traffic Routing with tun2proxy

### ISSUE THREAD

**Issue by dvir101** [tun2proxy/tun2proxy#138]
Hey @blechschmidt  :)

I’m curious if tun2proxy can be used similarly to Proxifier. Specifically, I’m looking to route traffic for a specific list of domains through a SOCKS proxy. The domains I want to route through the tun interface can only be resolved internally through a private DNS server that isn’t exposed to the internet, so basic iptables rules won’t work. My goal is to ensure these domains are resolved via the SOCKS proxy and that only their associated traffic is routed through the tun interface. All other traffic should flow normally without passing through the tun interface.

Would this be feasible with tun2proxy as it currently stands, or would it require additional functionality? Any guidance or suggestions you can provide would be greatly appreciated.

Thank you for your hard work on this project. It’s made a significant difference in my networking toolkit.

Best regards,

Dvir

**Comment by blechschmidt** [comment]
Hi @dvir101,

currently, that would not be feasible. However, implementing that feature would be relatively straightforward regarding the logic.

DNS handling logic is implemented here: https://github.com/tun2proxy/tun2proxy/blob/3f76ccec97340392acc595057e10ac0895f3b834/src/lib.rs#L276-L311

So you can see that we already support DNS over TCP and virtual DNS. For DNS over TCP, UDP packets are intercepted and forwarded to the desired DNS resolver, i.e. the response returns the real IP address of the destination domain. For virtual DNS, whenever we see a query for a DNS name, an IP address from 198.18.0.0/15 (currently hardcoded) is returned and we remember that in an IP to name mapping. Whenever we see connection to one of the remembered IP addresses, we ask the proxy to connect to the name instead of the destination IP.

Given this explanation, the logic for implementing that feature is relatively straightforward.

1. Build a data structure to determine whether a target name should be resolved through the proxy (e.g. a domain trie or a hash set).
2. If that is the case, behave like virtual DNS, i.e. return an address from 198.18.0.0/15.
3. Otherwise, forward the DNS query to the system's DNS resolver, which needs to be read from the corresponding configuration location (e.g. `/etc/resolv.conf` on Linux).

What is important here would be to only set up a route to the tunnel interface for 198.18.0.0/15 instead of 0.0.0.0/0 as it is done in the setup mode. Then, connections resolved through virtual DNS would go through the proxy.

Kind regards,
Birk

**Comment by blechschmidt** [comment]
Hi @dvir101,

thank you for your kind words. Unfortunately, this is not possible with the current feature set. To resolve DNS names through the proxy, tun2proxy's built-in DNS resolver has to be used. This is what virtual DNS does. Whenever it sees a DNS query, it replies with an IP address from 198.18.0.0/15 (currently hardcoded) and remembers an IP address to name mapping for the queried DNS name. Whenever we see a connection to that IP address, we then ask the proxy to connect to the DNS name instead of the IP address.

However, we currently lack the functionality to forward DNS queries to the configured system resolver (which could be obtained by reading the corresponding system configuration, e.g. `/etc/resolv.conf` on Linux) and we lack the functionality to tell the DNS proxy to differentiate between specific domains.

Logically, implementing that functionality would be quite straightforward:

1. Implement some data structure (e.g. a domain trie or hash set) that is filled with the domains that should be resolved through the proxy.
2. If a domain should be resolved through the proxy, just use virtual DNS.
3. Otherwise, forward the query to the system's DNS resolver.

What would be crucial here is to not make use of `--setup` which would automatically set up a route for 0.0.0.0/0 through the tunnel interface. Instead, only 198.18.0.0/15 should be configured to be routed through the tunnel interface. Then, virtual DNS would return IP address from that space and connections would always go through the tunnel. Other connections not destined to an IP from that space would not be routed through the tunnel.

Kind regads,
Birk

**Comment by ssrlive** [comment]
Perhaps this script can help. https://github.com/tun2proxy/tun2proxy/blob/master/scripts/iperf3.sh
