### ISSUE TITLE
dns over udp?

### ISSUE THREAD

**Issue by eric-gitta-moore** [tun2proxy/tun2proxy#146]
If the socks currently used supports udp, is there a way to directly transmit dns queries?

An alternative is to use over-tcp and manually specify -DNs-addr as the upstream dns

**Comment by ssrlive** [comment]
Since the destination addresses of DNS queries sent to tun are all tun's gateways (for example, 10.0.0.1), tun2proxy must be assigned a real DNS server (the default is 8.8.8.8) to complete the real DNS query.

Currently tun2proxy supports 3 ways to handle dns queries:
- fake-ip: Corresponds to the virtual-dns option.
- over-tcp: option with the same name.
- direct: Send directly using udp, as long as your socks5 server supports udp protocol.

https://github.com/tun2proxy/tun2proxy/wiki/Usage-(English)#linux
