### ISSUE TITLE
iOS: Feels really slow... 

### ISSUE THREAD

**Issue by Ignelos** [tun2proxy/tun2proxy#157]
Dear tun2proxy Developers,

I am experiencing significant performance issues while using tun2proxy. When connected through tun2proxy, the network speed is considerably slower compared to other applications using the same SOCKS5/HTTP proxy server.

Issue Details:
- Slow Speeds: Network throughput is much lower than expected when using tun2proxy.
- Proxy Comparison: Other applications that connect to the same SOCKS5 proxy exhibit normal or high speeds, indicating that the proxy server is not the bottleneck.
- 
Code Snippet:

Below is the network configuration code I’m using with tun2proxy:

```swift
// Create the network settings using the remote address
let settings = NEPacketTunnelNetworkSettings(tunnelRemoteAddress: "192.0.2.2")

// Configure IPv4 settings
let ipv4Settings = NEIPv4Settings(addresses: ["192.0.2.1"], subnetMasks: ["255.255.255.0"])
ipv4Settings.includedRoutes = [NEIPv4Route.default()]
settings.ipv4Settings = ipv4Settings

// Configure IPv6 settings
let ipv6Settings = NEIPv6Settings(addresses: ["2001:db8::1"], networkPrefixLengths: [64])
ipv6Settings.includedRoutes = [
    NEIPv6Route(destinationAddress: "::", networkPrefixLength: 1),
    NEIPv6Route(destinationAddress: "8000::", networkPrefixLength: 1),
]
settings.ipv6Settings = ipv6Settings

// Set the MTU
settings.mtu = 1500

// Configure DNS settings
let dnsSettings = NEDNSSettings(servers: ["8.8.8.8", "8.8.4.4", "127.0.0.1"])
settings.dnsSettings = dnsSettings

// Configure local proxy settings
let proxySettings = NEProxySettings()
let proxyServer = NEProxyServer(address: "127.0.0.1", port: 12323)
proxySettings.httpEnabled = true
proxySettings.httpServer = proxyServer
proxySettings.httpsEnabled = true
proxySettings.httpsServer = proxyServer
proxySettings.excludeSimpleHostnames = true
settings.proxySettings = proxySettings

return settings
```

Note:
- When `settings.proxySettings = proxySettings` is enabled nothing works... 

What I’ve Tried:

- Testing Different Applications: Verified that the SOCKS5 proxy is working efficiently by testing with other applications, which do not exhibit the slow speeds.
- Adjusting MTU Values: Experimented with different MTU sizes (e.g., 1200, 1400) without any noticeable improvement.
- Checking DNS Settings: Ensured that DNS servers are correctly configured and reachable. 
- Monitoring Resource Usage: Observed CPU and memory usage to rule out hardware limitations.

Note:

- I refactored your example to **Swift**
- I could not refactor system dns server list method from your example, could this be the issue ?

BTW: Thank you for this library it's hard to find something like this for iOS. 🙇

**Comment by Ignelos** [comment]
One more question... Why do we need to setup NEProxyServer on localhost? 🤔

**Comment by ssrlive** [comment]
The reason why I set this up is because I live in a __totalitarian country__, and any network protocol transmitted in __plaintext__ will be directly blocked by state network censorship (GFW). Therefore, the SOCKS server can only run on the local machine, and it serves both [DNS proxy](https://github.com/tun2proxy/dns2socks) intermediaries and [HTTP(S) proxy](https://github.com/tun2proxy/socks-hub) intermediaries. like this

![image](https://github.com/user-attachments/assets/8a93d400-5e67-4cc1-8064-05d423ee3c09)

After setting `settings.proxySettings = proxySettings`, 99%+ of the traffic will reach the __SOCK5 server__ through [HTTP2SOCKS](https://github.com/tun2proxy/socks-hub), and only a small amount of data will reach the __SOCK5 server__ through __TUN2PROXY__.

Because of the existence of the [DNS2SOCKS](https://github.com/tun2proxy/dns2socks) component, the first item in the DNS server list is set to 127.0.0.1.

As for the slow speed you mentioned, it is because we forcibly forward UDP traffic such as DNS queries through TCP. Performance is slower. However, under iOS, the reason why it cannot be forwarded directly through UDP has not been found yet. I hope this problem can be solved in the future.

In fact, I have a pure C implementation of the [tun2socks package](https://github.com/ssrlive/BadvpnTun2socks.git) for iOS, and I think the speed will not be compromised. You can give it a try.

I haven't developed on iOS for a long time. If you have time, you can try to fix this performance problem.

**Comment by Ignelos** [comment]
Thanks for Fast response! One more question will this new implementation supports http proxies? 🧐

**Comment by ssrlive** [comment]
which __new implementation__ ? you mean [this](https://github.com/ssrlive/BadvpnTun2socks.git) ? no, it support socks 5 only.

**Comment by Ignelos** [comment]
Yes [this](https://github.com/ssrlive/BadvpnTun2socks.git). Hmmm.... 😭
